name: CI

on: 
  push:
    branches: 
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish to Docker2
      uses: zenato/docker-action@master
      with:
        username: tattletech
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tattletech/mongo-backup-restore
        tag: latest
